# ---------------------------------------------  Server Port ------------------------------------------------------- #
server:
  port: 8080

spring:
# --------------------------------------------- Database use mysql5.5+    -----------------------------------#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# ---------------------------------------------  JPA ------------------------------------------------------- #
#  jpa:
#    hibernate:
# ---------------------------------------------   ------------------------------------------------------- #
#      ddl-auto: update
# ---------------------------------------------   ------------------------------------------------------- #
#    show-sql: true
# ---------------------------------------------   ------------------------------------------------- #
#    generate-ddl: true
# --------------------------------------------- mybatis ---------------------------------------------------- #
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

baidu:
  appid: 22686292
  appkey: my8ILKfyTfLIUgVvneG8zRDw
  secret: zxLVeEvdXRVjFGj0mTvEDg1U0WiIDWMV